plugins {
    id 'com.android.application'
}

android {
    namespace 'com.oac.nazhiyazi.op'
    compileSdk 35

    defaultConfig {
        applicationId 'com.oac.nazhiyazi.op'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
}
